stages:
  #  - premerge
  - build


vaas_docker_build:
  stage: build
  image: docker:latest
  services:
    - docker:dind

  script:
    - chown -R gitlab-runner /home/gitlab-runner/builds/H5mEtGm4h/0/vyoma_projects
    #- cd /home/gitlab-runner/builds/H5mEtGm4h/0/vyoma_projects
    #- ls
    #- rm -rf *
    #- echo fHKESNtr9Dh@FT | sudo -S rm -rf *
    # - sudo chmod 666 /var/run/docker.sock
    #- docker rm $(docker ps -aq)

  only:
    refs:
      - main
  tags:
   - pravartak_runner