stages:
  #  - premerge
  - build


vaas_docker_build:
  stage: build
  image: docker:latest
  services:
    - docker:dind

  script:
    - cd /home/gitlab-runner/builds
    - ls
    - sudo rm -rf *
    - sudo chmod 666 /var/run/docker.sock
    #- docker rm $(docker ps -aq)

  only:
    refs:
      - main
  tags:
   - pravartak_runner